global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'notifier-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9308']

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']
